sudo: false

language: go

go:
  - 1.11.x

git:
  depth: 1

install: true

notifications:
  email: false

before_script:
  - go get github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - go test -v -race ./...  # Run all the tests with the race detector enabled
